/**
 * Created by zhongzhengkai on 2017/5/20.
 */
export const lib  =
  [
    {
      "id": 1,
      "title": "品牌",
      "content": "买豪华SUV肯定要买最专业的。Jeep品牌，76年历史，全球SUV老大；全球年销量120多万, 比很多中国耳熟能详的大众化品牌全球量都多！说回大切，前身叫瓦格尼，全世界第一辆豪华SUV，整整54年历史；路虎揽胜才40多年历史，比Jeep晚了整整一代，宝马、奔驰、奥迪 SUV那就更没比了，才20年的SUV经验。所以买豪华SUV，Jeep的大切诺基是首选。",
      "url": "1",
      "valid": false,
      "description": "品牌",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 2,
      "title": "Quadra-Trac全时四驱系统",
      "content": "世界上第一款四驱车就是Jeep发明的，Jeep拥有13套四驱系统，是毫无争议的四驱之王。任何一个级别的SUV，Jeep车型的四驱能力都是最强的。",
      "url": "1",
      "valid": false,
      "description": "全路况能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 3,
      "title": "Selec-Terrain路况选择模式",
      "content": "豪华SUV讲求的不单是越野一项，而是全路况能力。大切诺基是同级车里唯一带7种路况模式选择的，几乎涵盖了您能经历的所有路况！只要看到大切的路况选择模式的选择旋纽，不用说都知道这才是真正具备全路况能力的专业豪华SUV！像大众途锐和宝马X5都是注重公路性能的SUV，路况选择模式要么是没有，要么就两三种，和大切根本不在一个级别上。",
      "url": "1",
      "valid": false,
      "description": "全路况能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 4,
      "title": "四轮空气悬挂",
      "content": "买这个级别的SUV，最好要配备一个功能强大的悬挂系统，因为各种路况需要的底盘高低不同。跑高速底盘要低一点，这样稳；路况条件差，底盘肯定要高一点，通过起来轻松；有老人小孩要坐车时，最好能让车身更低让他们方便上下车。这些需求大切诺基所配备的四轮独立空气悬挂都能满足你；它拥有同级最多的五级高度可调，您可以在试乘试驾时感受一下，什么叫花一辆车的钱，买5辆车的感受！",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 5,
      "title": "Uconnect智能操作系统",
      "content": "大切的Uconnect 人机交互系统是同级唯一键控、触控、声控三模式交互系统，如您在开车过程中需要调节空调，调节音响这样的事，大切可以让您不用低头，只需要开口说出来就搞定！这才是真正的“目不离路、手不离盘”！",
      "url": "1",
      "valid": false,
      "description": "人机交互",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 6,
      "title": "内饰豪华感",
      "content": "买这个级别的SUV，内饰的豪华感非常重要。大切所使用的豪华配置可以说是“武装到了牙齿”：顶级的真皮包裹中控台，Natural Plius的真皮座椅，前后排都有电加热功能，而且前排还有座椅通风，不管冬天夏天，坐上去都特别的舒服；玛莎拉蒂标准的绒面顶棚，橡木内饰。这都是百万级豪华SUV才有的配置。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 7,
      "title": "静音性能",
      "content": "真正的豪华车坐起来一定要安静，如果车辆行驶时声响太大，和朋友在车里交谈都困难，那面子上怎么过得去呢！大切诺基有五大静音技术，不但隔音做得好，关键是有同级车中唯一的主动降噪技术，开这样的车感觉不出这是一辆大型SUV，安静效果简直就像在劳斯莱斯里面一样。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 8,
      "title": "主动安全",
      "content": "主动安全方面，大切诺基不但有ACC+FCW，还有盲区监测，有了这些装备跑高速就轻松多了。那感觉有点像以前考驾照学开车时教练坐在旁边，一有情况教练就会提醒，我们要是还没反应教练就会帮忙踩刹车。您看当您在城市里驾驶时可能遇到前方车辆突然减速，这时候如果发现不及时可能会发生不必要的危险，大切的ACC+FCW会及时的提醒您帮您减速，在同一价位内只有大切有这样的安全配置，这就是大切的专业安全所在。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 9,
      "title": "被动安全",
      "content": "大切诺基的Unibody超高刚性车身，高强度钢材比例达到61%，获得世界上最严苛的碰撞试验IIHS“最安全车型”的称号。大切就像一座移动的钢铁堡垒，安全性毋庸置疑！",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 10,
      "title": "发动机",
      "content": "大切配备的是连续3年获得“世界十佳”发动机称号的Pentastar发动机，在加速时的平稳性以及动力性能，让您驾车游刃有余。而涡轮增压车，虽然动力性还可以，但驾驶舒适性和档次感真的不能和大切的大排量V6自然吸气发动机媲美。这就是大切诺基的专业所在。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 11,
      "title": "变速箱",
      "content": "大切拥有和几百万的宾利、玛莎拉蒂一样的ZF 8速变速箱，换挡平顺性和档次感不言而喻，性价比超高。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 12,
      "title": "动力组合",
      "content": "买豪华SUV，肯定要选大排量V6自然吸气的，再配合ZF的8AT，动力方面就不多说了。开这样的车出去，肯定比开个4缸2.0排量的车体面。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 13,
      "title": "品牌二手车价值",
      "content": "评价二手车是否值钱的标准有以下几点：\n1、品牌：在SUV领域里Jeep绝对比同级车要专业、高端，同样是二手车，更专业的车型，衬托更专业的您；\n2、保有量：大切的销量每年都在增加；\n像大切这样的车，二手车绝对保值。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 14,
      "title": "燃油经济性",
      "content": "大切的Pentastar发动机平顺性好、油耗低，配合ZF8速变速箱，最大续航里程1200公里，一箱油从北京到上海，而且在豪华SUV采用大排量V6发动机的车里，大切是唯一一个工信部测试综合油耗10升以内的车型。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 15,
      "title": "保养费用",
      "content": "您都买到这个级别的车了，要是总和您说这个便宜那个便宜的，也不太合适。但是还是要和您说一句，大切售后的保养费用真的不贵。虽然保养价格比宝马、奥迪便宜，但是您享受的服务一点不打折扣，您有时间可以到售后休息区看看，提前体验一下我们的售后服务。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 16,
      "title": "品牌",
      "content": "买东西牌子最重要，就像您买运动鞋买耐克的，买相机买索尼的。买SUV就要买Jeep的因为Jeep做SUV最专业；\nSUV就是由Jeep发明，Jeep76年只做SUV，比做轿车的其他品牌在专业性上有毋庸置疑的实力，驾驶Jeep也更能体现您的专业眼光。",
      "url": "1",
      "valid": false,
      "description": "品牌",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 17,
      "title": "ActiveDrive智能四驱系统",
      "content": "说到四驱这个级别Jeep说第二，没人敢说第一；\n自由光拥有同级能力最强的四驱，响应速度超快，从两驱切换到四驱只需要0.2秒，比眨眼时间还快；自由光拥有同级最省油的四驱，当以两驱状态行驶时，后桥完全分离，动力100%保留在前轮，不浪费一滴油；竞品用的普通四驱，即使是两驱的时候传动轴依然在运转，不但没有驱动力，还白白浪费油耗。所以说买四驱车一定要买四驱能力最强的Jeep自由光。",
      "url": "1",
      "valid": false,
      "description": "四驱能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 18,
      "title": "Selec-Terrain路况选择模式系统",
      "content": "自由光是同级唯一具备路况自选模式的SUV，懂车的朋友一看就知道，您买的是专业级的车！自由光有4种路况选择模式：自动、运动、雪地、泥地，您只需要根据路况调节旋钮。自由光除了调整四轮驱动力之外还会自动调整整车12个单元来帮您顺利通过不良路况，让您一键变成全路况达人。",
      "url": "1",
      "valid": false,
      "description": "四驱能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 19,
      "title": "底盘结构",
      "content": "自由光采用四轮独立悬挂设计，乘坐舒适性更好。相比普通SUV，自由光的悬挂行程更长，前170mm，后198mm，在颠簸及复杂路面，更充分的接触地面，缓震效果和抓地力都更好；我们做过很多对比测试，几台车通过相同的颠簸路面，别的车颠的很厉害，而自由光坐在车里感觉就像车轮底下铺了一层厚厚的地毯一样舒服。",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 20,
      "title": "减震器",
      "content": "自由光的减震器采用的是同级最先进的FSD频敏阻尼可变减震器，同级其他车用的普通悬挂，要么太硬，操控性是好了，但舒适性太差了；要么太软，舒适性很好，操控性完全没有了，而自由光的减震器软硬是根据路面情况软硬自动调节的，想软就软想硬就硬，这种减震器都是在专业级的改装车上才见得到的。",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 21,
      "title": "大尺寸刹车盘",
      "content": "自由光的刹车盘有两点要向您介绍一下\n第一点：品牌大，保时捷御用刹车供应商布雷博（Brembo）提供的刹车盘；\n第二点：尺寸大，而且前后尺寸几乎一样大。这才是专业的SUV应该有的。而其他品牌竞品的后轮刹车盘比前轮都要小很多，其实就是按照轿车的标准设计的，安全性能的差别不言而喻！",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 22,
      "title": "Uconnect智能操作系统",
      "content": "自由光配备的Uconnect是套非常实用的车载娱乐系统，声控、触控、键控三控合一。车上的很多功能都可以通过8.4寸的屏幕来操作非常方便。而且一些常用功能，比如说调节温度、听音乐、打电话，直接语音便可以实现，真正让您做到眼不离路，手不离盘轻松享受驾车生活。",
      "url": "1",
      "valid": false,
      "description": "人机交互",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 23,
      "title": "Uconnect LIVE",
      "content": "现在人越来越离不开手机了，因为上面有很多实用便捷的功能。但是如果您开车的时候还操作手机就会大大影响行车安全性，有了自由光您就无需再担心这点。它的Uconnect LIVE功能，把手机上很多实用功能都移植到了车机上，比如您想看个天气、听个音乐、找个饭店、查个地图，都可以在8.4寸中控屏幕上操作，简单便捷，无需再拿出手机。",
      "url": "1",
      "valid": false,
      "description": "人机交互",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 24,
      "title": "座椅舒适性",
      "content": "自由光座椅采用的是Nappa真皮，像Miu Miu、Prada有几款包，用的就是相同的皮质工艺，而且小小一个包都是上万的。这种皮质只有在70万以上的车才能看得见，自由光这套座椅的皮成本都要1万多；自由光座椅采用SUV专项设计，增加座椅底部支架，减缓颠簸路面冲击，乘坐更舒服；而且在座椅的不同部位，填充海绵采用不同硬度，支撑性和包覆性兼顾；坐在车上只有一种感受，那就是舒服！",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 25,
      "title": "乘坐空间",
      "content": "其实美国车空间舒适性要求很高，因为美国人体型都比较健硕，自由光在美国卖的非常好，这就说明自由光的空间特别舒适。您可以通过实车体验全方位感受自由光带来的舒适性，座椅非常宽大，无论是腿部空间，还是肩部空间都是同级占优的。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 26,
      "title": "安全性概述",
      "content": "您开车出门车上坐的不是亲人就是朋友，安全性是您必不可少要关注的方面。在其他车还在分主动安全被动安全的时候，自由光已经将安全升级为防患、预警、保护了。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 27,
      "title": "防患",
      "content": "防患就是通过科技配置尽量避免事故的发生，比如说ACC自适应巡航，只要设置好跟车距离，它就能做到：自动保持车距，前车快它就快，前车慢它就慢，前车停它就停，绝对安全；还有侧盲区监测系统、车道偏离警示、主动式胎压监测等配置，为您的行车保驾护航。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 28,
      "title": "预警",
      "content": "预警就是即将发生事故的时候通过科技配备尽量避免事故或减少事故损失。比如说FCW前撞预警系统，在即将发生追尾事故时，先通过声音提示危险来临，然后帮助您踩刹车；还有ESC、电子防翻滚系统等等，进一步保障您的安全。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 29,
      "title": "保护",
      "content": "保护指的就是事故发生后尽量保证车内驾乘人员的安全，自由光是同级唯一2.4L车型全系标配侧气帘的车型，全车高达7个气囊、整车高达65%高刚性钢材，最高强度达到1350Map。在世界上最严苛的北美IIHS碰撞实验当中获得了最高等级的安全评定，而且自由光的车顶能承受5倍自身重量，奥迪Q5能承受4.41倍、宝马X3能承受4.69倍，自由光的车顶承重能力比Q5和X3都要好。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 30,
      "title": "发动机",
      "content": "自由光2.4L发动机采用的是菲克集团投入10亿美金研发的MultiAir-2技术，它能根据路况自动调节气门正时和升程，类似的技术全球只有我们和宝马才有。有了这样的技术无论在扭矩还是功率上，均有明显加强，油耗也明显降低，百公里只有8.1L。最关键的是它只需要加93（92）号汽油，同级其他涡轮增压车型都需要97（95)号汽油，实用性也是自由光更胜一筹。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 31,
      "title": "变速箱",
      "content": "自由光同级唯一配备9AT变速箱，比6AT加速快2秒，油耗低16%，换挡几乎没感觉，就是平顺！9AT奔驰的车也在用，但是要40多万才能买得到。竞品的双离合变速箱和自由光的9AT根本不是一个级别的东西。当车速开到120KM的时候发动机的转速才1600转，竞品都在2000转左右，相当省油。懂车的人都会选择档位更多的车。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 32,
      "title": "动力组合",
      "content": "自由光的动力总成可以用耐用、可靠、平顺、省油来评价；\n耐用是指发动机不需要像竞品一样更换涡轮增压；可靠是指对燃油标号要求低，开到哪里都能加油；平顺是指自然吸气发动机加速更线性，不会出现涡轮增压的车动力迟滞感觉，9AT换挡平顺性远超同级别车的换挡平顺性；省油是指MultiAir-2根据路况自动合理分配喷油量，以及9AT在高速上为您节省的油耗。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 33,
      "title": "品牌二手车价值",
      "content": "评价二手车是否值钱的标准有以下几点：\n1、保有量，自由光去年一年就卖了10多万辆，而且每天都在增加，这么大的保有量不用担心他不保值；\n2、使用费用，自由光是自然吸气发动机，即使已经跑了10万公里，也不用换涡轮增压，肯定比用涡轮增压发动机的二手车值钱；\n3、品牌，在SUV领域里Jeep绝对比同级车要专业、高端，同样是二手车，肯定要买个更专业的车型；\n像自由光这样的车，绝对保值。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 34,
      "title": "燃油经济性",
      "content": "车省不省油是看车有没有用省油的技术。自由光为了提升燃油经济性花了大量的成本，发动机MultiAir-2技术、9AT变速箱、智能启停技术、主动进气格栅、节能轮胎等等。即使是四驱车型，工信部测试的综合路况油耗也就8.5L。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 35,
      "title": "保养费用",
      "content": "我们的保养价格和途观、昂科威都差不多。\n虽然保养费用差不多，但是途观所使用的机油比我们低好几个档次！自由光的机油是：壳牌SN 0W-20 高品质全合成机油，途观用的是连品牌都没有的 所谓“原厂机油”，型号是： SL 5W-40，跟新桑塔纳使用的机油型号一致。\n全新Jeep自由光是专业级城市SUV，机油需要满足各种复杂路况的使用需求，比如长途驾驶、长期高负荷运转、承受高热或高寒的用车温度。自由光使用的壳牌SN 0W-20就是这样的专业级机油。它拥有超乎寻常的抗磨损能力；比常规机油在更高温度、更低温度下都有更好的流动性；而且更省油。那些所谓的“原厂机油”也只能满足城市的代步需求，和专业级还差的很远。不仅如此，我们的常用保养件，如火花塞、机油滤芯等，在保证了专业级品质的同时，比途观的价格更低。\n自由光不仅机油用的是最高标准的，其他部件也一样。比如：空调滤芯是全球知名马瑞利品牌提供的，能过滤PM2.5；刹车片用的是保时捷的御用品牌意大利布雷博的，而且尺寸也比途观的大，成本肯定不一样。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 36,
      "title": "品牌",
      "content": "Jeep是世界上最专业的SUV品牌，行业里的很多第一也是Jeep创造并保持的。13万起就能买到一台Jeep，价格不高，逼格很高。现在市面上能看到的小型SUV基本上都是SUV的外壳加上一个轿车的底盘组成的，和买一个轿车没有什么区别。花同样的钱肯定要买一台逼格更高、更专业的车。",
      "url": "1",
      "valid": false,
      "description": "品牌价值",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 37,
      "title": "ActiveDrive Low智能四驱系统",
      "content": "自由侠的ActiveDrive Low四驱系统是同级唯一能把动力100%作用在前轮而且能够完全断开后轴，两驱行驶时动力损失最小的四驱系统，也是最省油的四驱系统。仅需0.2秒就能从两驱切换成四驱，人眨眼的速度约0.25秒，比人眨眼速度还要快。",
      "url": "1",
      "valid": false,
      "description": "四驱能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 38,
      "title": "Selec-Terrain路况模式自选系统",
      "content": "自由侠是同级唯一配备路况选择模式的车，提供多达5种路况选择模式，而且还有同级唯一的低速扭矩放大功能，不需要您有太多的全路况驾驶的经验，只要根据路况，将模式旋钮调节到与当前路况匹配的位置，就可以放心驾驶。节假日要想带着朋友一起出去游玩，开着自由侠会带您去到风景更独特的地方。",
      "url": "1",
      "valid": false,
      "description": "四驱能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 39,
      "title": "底盘结构",
      "content": "自由侠是同级唯一配备四轮独立悬架的车型。相比其他使用非独立悬架的SUV舒适性更好，操控性更强。市面上的其他车型的悬挂结构会以价格进行区分，一般20万以上的车都是和自由侠一样使用四轮独立悬架，而10万以内的车基本都和其他小型SUV一样采用非独立悬架。自由侠的这个超值配置值得拥有。",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 40,
      "title": "减震器",
      "content": "自由侠是同级唯一采用自适应减震器的车型，这个减震器一般都用在专业级改装车上的。它的好处就是自动根据路况进行软硬调节，颠簸路时会自动变软，提升舒适性；急转弯或激烈驾驶时会自动变硬，提升操控性。自由侠拥有其他品牌车型无法比拟的高端配置。",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 41,
      "title": "Uconnect智能操作系统",
      "content": "自由侠配备的Uconnect是套非常实用的车载娱乐系统，声控、触控、键控三控合一。车上的很多功能都可以通过中控屏幕来操作非常方便，而且一些常用功能，比如说想调节温度、听音乐、打电话，直接跟它说就可以了。有了这套系统的帮忙，真正让您做到眼不离路，手不离盘，轻松享受驾车生活。",
      "url": "1",
      "valid": false,
      "description": "人机交互",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 42,
      "title": "Uconnect LIVE",
      "content": "现代人越来越离不开手机，正是由于手机提供的丰富多样且实用便捷的功能。但是如果您开车的时候还操作手机的话就会大大影响行车安全性。有了自由侠就无需再担心这点，它的Uconnect LIVE功能，把手机上很多实用功能都移植到了车机上，比如您想看个天气、听个音乐、找个饭店、查个地图，都可以在中控屏幕上操作，简单便捷，无需再拿出手机。",
      "url": "1",
      "valid": false,
      "description": "人机交互",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 43,
      "title": "内饰设计",
      "content": "自由侠是同级唯一获得“沃德十佳内饰”的车型，和它同期获奖的车型还有宝马I3、奔驰的C400，这些车都要卖好几十万。这个奖项评级标准非常高，内饰首先要设计的时尚、美观；各种按键旋钮操作起来简单方便；所选用的材料必须环保，耐磨、耐刮擦性能也要达到世界级别的标准。花同样的钱，肯定要买世界级设计标准的车。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 44,
      "title": "乘坐空间",
      "content": "车宽和车高是评价一辆车乘坐空间是否舒适的两条重要的参考指标。车高代表您的头部空间，车宽代表您的肩部空间。自由侠这两项数据都是同级最大的，您和家人可以实车体验一下自由侠同级最宽敞的头部空间和肩部空间。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 45,
      "title": "主动安全",
      "content": "自由侠全系标配十大主动安全科技，一些耳熟能详的安全配备，比如车身稳定系统、电子防翻滚系统、紧急刹车辅助啊，这些都是全系标配。还有像电子限滑、动态转向辅助、制动力失效补偿这几个二三十万的车才配备主动安全科技，自由侠也是全系标配。如此完备的安全配备在同级其他车型上是很难遇到的。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 46,
      "title": "被动安全",
      "content": "自由侠拥有Jeep76年以来造过的最硬的车身，整车70%的高强度钢，比日系车高出接近一倍。工厂的工程师们曾开玩笑说这不是在造车，这是在造“民用坦克”。自由侠也通过了世界上最严苛的碰撞试验E-NCAP五星级的评定。开”民用坦克“出门，安全性毋庸置疑。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 47,
      "title": "发动机",
      "content": "自由侠搭载的1.4T发动机拥有同级最高的79KW的升功率，无论是功率还是扭矩，比本田1.8L的发动机都要强；而且只需要加93（92）号汽油，不挑食。\n2.0L的发动机用的和自由光的是一样的，动力性、可靠性完全不用担心。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 48,
      "title": "变速箱",
      "content": "自由侠拥有同级最高”档“变速箱；\n与1.4T车型匹配的是7速DDCT变速箱，它拥有同级最多的档位，研发平台源自著名运动车型品牌阿尔法罗密欧，传动效率比传统自动挡高33%，不仅换挡更快，而且油耗也比传统的6AT变速箱低15%。\n与2.0L发动机匹配的是目前全球最先进的ZF 9AT变速箱，起步猛、换挡顺、高速省。而且除了Jeep品牌，9AT配备的其他品牌至少要35万以上。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 49,
      "title": "动力组合",
      "content": "在比较动力总成的时候无非就是想要动力强点、油耗省点的车，同级最强动力、媲美日系车的油耗，1.4T+7DDCT这套动力总成完全能满足您；\n如果您选择四驱车型的话，2.0L+9AT的动力组合无论是平顺性，动力性都是完胜同级。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 50,
      "title": "品牌二手车价值",
      "content": "评价二手车是否值钱的标准有以下几点：\n1、品牌：在SUV领域里Jeep绝对比同级车要专业、高端。同样是二手车，肯定要买个更专业的车型；\n2、保有量：自由侠的销量每个月都在上涨，买个车至少可以使用3-5年，3-5年后自由侠的保有量将会是一个很庞大的数字；\n自由侠的二手车保值率您无需担心。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 51,
      "title": "燃油经济性",
      "content": "自由侠车身用了比同级车更多的70%的高刚性钢材，安全性更高；发动机升功率同级最强的同时，综合工况油耗和同级车型差不多。全系标配发动机启停系统，光这套系统每年也能为您节省1000多块的油钱。像自由侠这样安全、动力好、油耗省的车，市面上很难遇到。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 52,
      "title": "保养费用",
      "content": "Jeep品牌比同级车都要高档，但保养费用和同级车型却是差不多的。而且在费用差不多的情况下，各种配备却比竞品好很多。比如自由侠的空气滤芯是防PM2.5的，同级车型都是普通的，自由侠价格不高，品质更好。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 53,
      "title": "品牌",
      "content": "现在为什么更多人喜欢买SUV，就是出于SUV比轿车有更多的优势。但既然选择了SUV，推荐您选择一个更专业的品牌，就像您买运动鞋要买耐克的，买西装要买阿玛尼的，因为他们专业。买SUV肯定要买Jeep，因为SUV就是Jeep发明的，76年来只做专业SUV。这和那些半路出家的轿车品牌对比的优势性不言而喻，开出去也更体面。",
      "url": "1",
      "valid": false,
      "description": "品牌",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 54,
      "title": "Trailhawk车型",
      "content": "Jeep第一次国产Trailhawk车型的就是指南者。Jeep品牌的Trailhawk车型，就相当于宝马的M系列，奔驰的AMG系列，都代表着拥有顶级的能力。而且Trailhawk车型还通过了与美国军方合作的Trail Rated四驱能力认证，在40万以内的SUV里，它的性能最强。",
      "url": "1",
      "valid": false,
      "description": "四驱能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 55,
      "title": "Active Drive Low智能四驱系统",
      "content": "指南者的ActiveDrive Low四驱系统拥有同级唯一后桥分离技术，两驱四驱自动切换，而且在两驱的时候传动轴也停止转动，要比同级的四驱系统省不少的油；它还具备同级唯一低速扭矩放大功能；同级唯一真正陡坡缓降功能，利用四驱系统自动控制的机械制动，相比竞品靠刹车实现的所谓陡坡缓降强大太多。",
      "url": "1",
      "valid": false,
      "description": "四驱能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 56,
      "title": "Active Drive Low智能四驱系统",
      "content": "指南者是同级唯一配备路况选择模式的车，而且提供多达5种路况选择模式，还有同级唯一的低速扭矩放大功能，无需您有太多的全路况驾驶的经验，只需要您根据路况将模式旋钮调节到与当前路况匹配的位置，就可以放心的驾驶。",
      "url": "1",
      "valid": false,
      "description": "四驱能力",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 57,
      "title": "底盘结构",
      "content": "指南者采用前麦佛逊后多连杆的四轮独立悬架，舒适性非常好，展厅提供试乘试驾服务，您可以在试驾中亲身体验。",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 58,
      "title": "减震器",
      "content": "指南者是同级唯一配备自适应减震器的，同级其他车用的普通悬挂：要么太硬，操控性是好了，但舒适性太差了；要么太软，舒适性很好，操控性完全没有了。而指南者的减震器软硬是根据路面情况软硬自动调节的，想软就软想硬就硬，这种减震器都是在专业级的改装车上才见得到的。",
      "url": "1",
      "valid": false,
      "description": "底盘悬挂",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 59,
      "title": "Uconnect智能操作系统",
      "content": "指南者配备的Uconnect是套非常实用的车载娱乐系统，声控、触控、键控三控合一。车上的很多功能都可以通过8.4寸的屏幕来操作非常方便。一些常用功能，比如说调节温度、听音乐、打电话，直接语音便可以实现，真正让您做到眼不离路，手不离盘还能轻松享受驾车生活。",
      "url": "1",
      "valid": false,
      "description": "人机交互",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 60,
      "title": "Uconnect LIVE",
      "content": "现在人越来越离不开手机了，因为上面有很多实用的功能。但是如果您开车的时候还操作手机就会影响行车安全性。指南者的Uconnect LIVE功能，把手机上很多实用功能都移植到了车机上，比如您想看个天气、听个音乐、找个饭店、查个地图，都可以在8.4寸中控屏幕上直接操作，简单便捷，无需再拿出手机。",
      "url": "1",
      "valid": false,
      "description": "人机交互",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 61,
      "title": "前排座椅舒适性",
      "content": "指南者的座椅包裹性和支撑性都很好，而且非常耐用。评价它有个词叫“一把椅子，10年如新”，工程师在设计之初，在座椅的上面用150斤的重物，经过20万次的压力测试不变形，为的就是您买回去之后用了很多年，座椅的支撑性和包裹性还和新的没有太大的区别。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 62,
      "title": "后排座椅舒适性",
      "content": "指南者的椅子采用的是南美进口头层小牛皮，而且后排座椅的长度、宽度、椅背高度都是同级最大的，为的就是让您更舒服。靠背的角度是最适合亚洲人体乘坐的23度，让您和家人都能拥有最舒适的坐姿。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 63,
      "title": "乘坐空间",
      "content": "第二排最重要的就是腿部空间，市面上很多车都会把座椅做的短一些来突显后排空间，这样做不但乘坐空间没有改善，还失去了对腿部的支撑。指南者当然不会这么做，它拥有同级最大的座椅不但为腿部提供良好的支撑性，还能为您提供两拳的后排腿部空间。",
      "url": "1",
      "valid": false,
      "description": "舒适性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 64,
      "title": "安全性概述",
      "content": "您开车出门，车上坐的不是亲人就是朋友，安全性是您必不可少要关注的方面，在其他车还在分主动安全被动安全的时候，指南者已经将安全升级为防患、预警、保护了。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 65,
      "title": "防患",
      "content": "防患就是通过科技配置尽量避免事故的发生，比如说ACC自适应巡航，只要设置好跟车距离，它将会自动保持车距，前车快我就快，前车慢我就慢，前车停我就停，绝对安全；还有侧盲区监测系统、车道偏离警示、主动式胎压监测等配置，为您的行车保驾护航。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 66,
      "title": "预警",
      "content": "预警就是即将发生事故的时候通过科技配备尽量避免事故或减少事故损失。比如说FCW前撞预警系统，在即将发生追尾事故时，先通过声音提示危险来临，然后帮助您踩刹车；还有ESC、电子防翻滚系统等等，进一步保障您的行车安全。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 67,
      "title": "保护",
      "content": "保护指的就是事故发生后尽量保证车内驾乘人员的安全，整车高达64%高刚性钢材，最高强度达到1300Map-1600Map，而且指南者的车顶能承受5倍自身重量，远超奥迪Q5能承受4.41倍、宝马X3能承受4.69倍。",
      "url": "1",
      "valid": false,
      "description": "安全性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 68,
      "title": "发动机",
      "content": "一台发动机的好坏要看三点：\n1、看技术：指南者1.4T发动机采用的是目前菲克集团最先进的MultiAir2进气技术，这项技术领先同级车几个时代。类似的技术只有宝马拥有；\n2、看动力：这款1.4T发动机的动力比大众的1.8T还要牛，在内部对比测试中0-100Km加速10秒以内就能完成；\n3、看油耗：指南者这台1.4T发动机百公里综合油耗只有7.2L，比日本车还要省油；\n1.4T发动机凭借技术新、动力强、油耗低的特点获得了“欧洲十佳发动机”称号；\n2.4L的发动机与自由光的相同，而且自由光已经有十几万的车主在见证它的性能了，用着更放心。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 69,
      "title": "变速箱",
      "content": "与1.4T发动机配合的是全新调校的7DDCT变速箱，传动效率比传统自动挡高33%，油耗也比传统的6AT变速箱低15%；\n与2.4L发动机配合的是目前全球最先进的ZF 9AT变速箱，起步猛、换挡顺、高速省，而且除了Jeep品牌，您要想买到9AT至少要35万以上。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 70,
      "title": "动力组合",
      "content": "动力总成的评价标准无非三点，技术新、动力强、油耗低，我们1.4T的车型完全能满足您的要求。\n您要是选择Trailhawk车型的话，2.4L+9AT的动力组合无论是平顺性，动力性都是完胜同级。",
      "url": "1",
      "valid": false,
      "description": "操控性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 71,
      "title": "品牌二手车价值",
      "content": "评价二手车是否值钱的标准有以下几点：\n1、保有量：指南者现在的销量非常的好，而且每天都在增加，这么大的保有量不用担心它不保值；\n2、使用费用：指南者油耗低、保养费用也不高，二手车肯定保值的；\n3、品牌：在SUV领域里Jeep绝对比同级车要专业、高端，同样是二手车，肯定买个更专业的；\n像指南者这样的车，保值率不用担心。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 72,
      "title": "燃油经济性",
      "content": "指南者1.4T车型综合油耗只有7.2L，比日系车还要省油。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 73,
      "title": "保养费用",
      "content": "指南者的保养费用和同级其他品牌的同级车型差不多，但是指南者用的机油是全球指定的0W30高标号机油，比同级车高了几个档次。价格不高，品质更好。",
      "url": "1",
      "valid": false,
      "description": "经济性",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 1
    },
    {
      "id": 74,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户在店交流的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 询问今日服务或试驾感受</p>\n<p>4. 加深客户对品牌和经销店的认可（通过回顾当日服务的细节）</p>\n<p>5. 再次明确客户意向车型（再次向客户进行车型推荐及强化，强调品牌独有技术或功能）</p>\n<p>6. 询问客户是否还有关注点或其他疑问（可直接询问，同时为下一次接触留下伏笔）</p>\n<p>7.（若客户表示无明显关注点或疑问）可适当引导客户对产品或品牌作进一步的了解，以激发客户进一步的购车欲望，同时为下一次的接触留下伏笔</p>\n<p>8.强调会给客户进行优惠活动信息传递，与客户加深联系（申请添加微信）</p>\n<p>9. 向客户再次表达感谢，并预约下一次的接触时间（回访或邀请到店）</p>",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 75,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆并查看与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3.（以上次到店体验或印象比较深刻的信息点或遗留的问题点）唤起客户回忆并做客户重点关注的卖点提醒</p>\n<p>4.1.日常跟进：</p>                                                                                                                    \n<p>1）情感维系，前期先打破僵局，取得良好沟通的开始；</p>                                                       \n<p>2）了解客户最新动态；</p>                                                                                                       \n<p>3）简单的需求分析，判定级别是否提升：</p>                                                                             \n<p>4.）向客户介绍最新价格优惠力度、装潢标准、服务、保险、上牌等具体信息</p>\n<p>4.2.日常邀约（二次到店邀约）：告知致电目的 </p>                                                                     \n<p>5. 确认对方方便到店的时间（都问封闭式问题，最多不超过三个问题，eg:您是平时还是周末有时间？那是周六还是周日？您看我们约在周六上午十点可以吗？）；</p>                                       \n<p>6.告知来店好处（结合之前了解的客户的喜好特点来设定利益，利用喜好关联来诱惑客户至店）</p>\n<p>7. 告知经销店的具体位置，并告知来店的方式（要求销售顾问对于经销店周边的环境要熟知）</p> \n<p>8.为下次联系留下伏笔（根据本次电话内容找出可跟进的话题，以备下次联系留下机会）；</p>       \n<p>9.再次做一下自我介绍，加深客户的印象，并强调到店一定记得找自己 </p>                                                              \n<p>10.询问对方是否还有其他需要帮助的，若有则继续提供咨询服务；</p>                                        \n<p>11.若无则感谢关注并祝福； </p>                                                                                                \n<p>12.等对方挂机后再挂机（若对方没有先挂，请对方先挂机）</p>                                                 \n<p>13.发送短信或者微信并再次提出邀请（可根据电话内容设置不同话术内容）</p>",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 76,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 简单告知活动主题（邀约试驾、店内活动、.....）</p>\n<p>4. 告知此次活动的特殊性（e.g. 店内优惠、到店礼包、…..）</p>\n<p>5. 突出该客户的专属性（e.g. 名额有限、专门针对某一类的客户组织的交谊会、…..）</p>                    \n<p>6.询问对方参加活动的意向程度</p>\n<p>6.1.若愿意参加， 与客户确认到店时间并且尝试邀请其亲朋好友一起到场 </p>\n<p>6.2.若客户产生拒绝邀约的意向，需探寻拒绝的原因，并作其他补救措施，告知大多数车主参加活动的兴趣点（举证法：举证一些其他客户关注的方面，尝试能否引起客户共鸣，达到从众的作用）</p>   \n<p>7.寻找话题点为下次联系留下伏笔 </p>                                                                                               \n<p>8.感谢关注并祝福</p>",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 77,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户在店交流的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 询问今日服务或试驾感受</p>\n<p>4. 加深客户对品牌和经销店的认可（通过回顾当日服务的细节）</p>\n<p>5. 再次明确客户意向车型（再次向客户进行车型推荐及强化，强调品牌独有技术或功能）</p>\n<p>6. 询问客户是否还有关注点或其他疑问（可直接询问，同时为下一次接触留下伏笔）</p>\n<p>7.（若客户表示无明显关注点或疑问）可适当引导客户对产品或品牌作进一步的了解，以激发客户进一步的购车欲望，同时为下一次的接触留下伏笔</p>\n<p>8.强调会给客户进行优惠活动信息传递，与客户加深联系（申请添加微信）</p>\n<p>9. 向客户再次表达感谢，并预约下一次的接触时间（回访或邀请到店）</p>",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 78,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆并查看与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3.（以上次到店体验或印象比较深刻的信息点或遗留的问题点）唤起客户回忆并做客户重点关注的卖点提醒</p>\n<p>4.1.日常跟进：</p>                                                                                                                    \n<p>1）情感维系，前期先打破僵局，取得良好沟通的开始；</p>                                                       \n<p>2）了解客户最新动态；</p>                                                                                                       \n<p>3）简单的需求分析，判定级别是否提升：</p>                                                                             \n<p>4.）向客户介绍最新价格优惠力度、装潢标准、服务、保险、上牌等具体信息</p>\n<p>4.2.日常邀约（二次到店邀约）：告知致电目的 </p>                                                                     \n<p>5. 确认对方方便到店的时间（都问封闭式问题，最多不超过三个问题，eg:您是平时还是周末有时间？那是周六还是周日？您看我们约在周六上午十点可以吗？）；</p>                                       \n<p>6.告知来店好处（结合之前了解的客户的喜好特点来设定利益，利用喜好关联来诱惑客户至店）</p>\n<p>7. 告知经销店的具体位置，并告知来店的方式（要求销售顾问对于经销店周边的环境要熟知）</p> \n<p>8.为下次联系留下伏笔（根据本次电话内容找出可跟进的话题，以备下次联系留下机会）；</p>       \n<p>9.再次做一下自我介绍，加深客户的印象，并强调到店一定记得找自己 </p>                                                              \n<p>10.询问对方是否还有其他需要帮助的，若有则继续提供咨询服务；</p>                                        \n<p>11.若无则感谢关注并祝福； </p>                                                                                                \n<p>12.等对方挂机后再挂机（若对方没有先挂，请对方先挂机）</p>                                                 \n<p>13.发送短信或者微信并再次提出邀请（可根据电话内容设置不同话术内容）</p>",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 79,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 简单告知活动主题（邀约试驾、店内活动、.....）</p>\n<p>4. 告知此次活动的特殊性（e.g. 店内优惠、到店礼包、…..）</p>\n<p>5. 突出该客户的专属性（e.g. 名额有限、专门针对某一类的客户组织的交谊会、…..）</p>                    \n<p>6.询问对方参加活动的意向程度</p>\n<p>6.1.若愿意参加， 与客户确认到店时间并且尝试邀请其亲朋好友一起到场 </p>\n<p>6.2.若客户产生拒绝邀约的意向，需探寻拒绝的原因，并作其他补救措施，告知大多数车主参加活动的兴趣点（举证法：举证一些其他客户关注的方面，尝试能否引起客户共鸣，达到从众的作用）</p>   \n<p>7.寻找话题点为下次联系留下伏笔 </p>                                                                                               \n<p>8.感谢关注并祝福</p>",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 80,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户在店交流的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 询问今日服务或试驾感受</p>\n<p>4. 加深客户对品牌和经销店的认可（通过回顾当日服务的细节）</p>\n<p>5. 再次明确客户意向车型（再次向客户进行车型推荐及强化，强调品牌独有技术或功能）</p>\n<p>6. 询问客户是否还有关注点或其他疑问（可直接询问，同时为下一次接触留下伏笔）</p>\n<p>7.（若客户表示无明显关注点或疑问）可适当引导客户对产品或品牌作进一步的了解，以激发客户进一步的购车欲望，同时为下一次的接触留下伏笔</p>\n<p>8.强调会给客户进行优惠活动信息传递，与客户加深联系（申请添加微信）</p>\n<p>9. 向客户再次表达感谢，并预约下一次的接触时间（回访或邀请到店）</p>",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 81,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆并查看与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3.（以上次到店体验或印象比较深刻的信息点或遗留的问题点）唤起客户回忆并做客户重点关注的卖点提醒</p>\n<p>4.1.日常跟进：</p>                                                                                                                    \n<p>1）情感维系，前期先打破僵局，取得良好沟通的开始；</p>                                                       \n<p>2）了解客户最新动态；</p>                                                                                                       \n<p>3）简单的需求分析，判定级别是否提升：</p>                                                                             \n<p>4.）向客户介绍最新价格优惠力度、装潢标准、服务、保险、上牌等具体信息</p>\n<p>4.2.日常邀约（二次到店邀约）：告知致电目的 </p>                                                                     \n<p>5. 确认对方方便到店的时间（都问封闭式问题，最多不超过三个问题，eg:您是平时还是周末有时间？那是周六还是周日？您看我们约在周六上午十点可以吗？）；</p>                                       \n<p>6.告知来店好处（结合之前了解的客户的喜好特点来设定利益，利用喜好关联来诱惑客户至店）</p>\n<p>7. 告知经销店的具体位置，并告知来店的方式（要求销售顾问对于经销店周边的环境要熟知）</p> \n<p>8.为下次联系留下伏笔（根据本次电话内容找出可跟进的话题，以备下次联系留下机会）；</p>       \n<p>9.再次做一下自我介绍，加深客户的印象，并强调到店一定记得找自己 </p>                                                              \n<p>10.询问对方是否还有其他需要帮助的，若有则继续提供咨询服务；</p>                                        \n<p>11.若无则感谢关注并祝福； </p>                                                                                                \n<p>12.等对方挂机后再挂机（若对方没有先挂，请对方先挂机）</p>                                                 \n<p>13.发送短信或者微信并再次提出邀请（可根据电话内容设置不同话术内容）</p>",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 82,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 简单告知活动主题（邀约试驾、店内活动、.....）</p>\n<p>4. 告知此次活动的特殊性（e.g. 店内优惠、到店礼包、…..）</p>\n<p>5. 突出该客户的专属性（e.g. 名额有限、专门针对某一类的客户组织的交谊会、…..）</p>                    \n<p>6.询问对方参加活动的意向程度</p>\n<p>6.1.若愿意参加， 与客户确认到店时间并且尝试邀请其亲朋好友一起到场 </p>\n<p>6.2.若客户产生拒绝邀约的意向，需探寻拒绝的原因，并作其他补救措施，告知大多数车主参加活动的兴趣点（举证法：举证一些其他客户关注的方面，尝试能否引起客户共鸣，达到从众的作用）</p>   \n<p>7.寻找话题点为下次联系留下伏笔 </p>                                                                                               \n<p>8.感谢关注并祝福</p>",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 83,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户在店交流的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 询问今日服务或试驾感受</p>\n<p>4. 加深客户对品牌和经销店的认可（通过回顾当日服务的细节）</p>\n<p>5. 再次明确客户意向车型（再次向客户进行车型推荐及强化，强调品牌独有技术或功能）</p>\n<p>6. 询问客户是否还有关注点或其他疑问（可直接询问，同时为下一次接触留下伏笔）</p>\n<p>7.（若客户表示无明显关注点或疑问）可适当引导客户对产品或品牌作进一步的了解，以激发客户进一步的购车欲望，同时为下一次的接触留下伏笔</p>\n<p>8.强调会给客户进行优惠活动信息传递，与客户加深联系（申请添加微信）</p>\n<p>9. 向客户再次表达感谢，并预约下一次的接触时间（回访或邀请到店）</p>",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 84,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆并查看与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3.（以上次到店体验或印象比较深刻的信息点或遗留的问题点）唤起客户回忆并做客户重点关注的卖点提醒</p>\n<p>4.1.日常跟进：</p>                                                                                                                    \n<p>1）情感维系，前期先打破僵局，取得良好沟通的开始；</p>                                                       \n<p>2）了解客户最新动态；</p>                                                                                                       \n<p>3）简单的需求分析，判定级别是否提升：</p>                                                                             \n<p>4.）向客户介绍最新价格优惠力度、装潢标准、服务、保险、上牌等具体信息</p>\n<p>4.2.日常邀约（二次到店邀约）：告知致电目的 </p>                                                                     \n<p>5. 确认对方方便到店的时间（都问封闭式问题，最多不超过三个问题，eg:您是平时还是周末有时间？那是周六还是周日？您看我们约在周六上午十点可以吗？）；</p>                                       \n<p>6.告知来店好处（结合之前了解的客户的喜好特点来设定利益，利用喜好关联来诱惑客户至店）</p>\n<p>7. 告知经销店的具体位置，并告知来店的方式（要求销售顾问对于经销店周边的环境要熟知）</p> \n<p>8.为下次联系留下伏笔（根据本次电话内容找出可跟进的话题，以备下次联系留下机会）；</p>       \n<p>9.再次做一下自我介绍，加深客户的印象，并强调到店一定记得找自己 </p>                                                              \n<p>10.询问对方是否还有其他需要帮助的，若有则继续提供咨询服务；</p>                                        \n<p>11.若无则感谢关注并祝福； </p>                                                                                                \n<p>12.等对方挂机后再挂机（若对方没有先挂，请对方先挂机）</p>                                                 \n<p>13.发送短信或者微信并再次提出邀请（可根据电话内容设置不同话术内容）</p>",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 85,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 简单告知活动主题（邀约试驾、店内活动、.....）</p>\n<p>4. 告知此次活动的特殊性（e.g. 店内优惠、到店礼包、…..）</p>\n<p>5. 突出该客户的专属性（e.g. 名额有限、专门针对某一类的客户组织的交谊会、…..）</p>                    \n<p>6.询问对方参加活动的意向程度</p>\n<p>6.1.若愿意参加， 与客户确认到店时间并且尝试邀请其亲朋好友一起到场 </p>\n<p>6.2.若客户产生拒绝邀约的意向，需探寻拒绝的原因，并作其他补救措施，告知大多数车主参加活动的兴趣点（举证法：举证一些其他客户关注的方面，尝试能否引起客户共鸣，达到从众的作用）</p>   \n<p>7.寻找话题点为下次联系留下伏笔 </p>                                                                                               \n<p>8.感谢关注并祝福</p>",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 86,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户在店交流的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 询问今日服务或试驾感受</p>\n<p>4. 加深客户对品牌和经销店的认可（通过回顾当日服务的细节）</p>\n<p>5. 再次明确客户意向车型（再次向客户进行车型推荐及强化，强调品牌独有技术或功能）</p>\n<p>6. 询问客户是否还有关注点或其他疑问（可直接询问，同时为下一次接触留下伏笔）</p>\n<p>7.（若客户表示无明显关注点或疑问）可适当引导客户对产品或品牌作进一步的了解，以激发客户进一步的购车欲望，同时为下一次的接触留下伏笔</p>\n<p>8.强调会给客户进行优惠活动信息传递，与客户加深联系（申请添加微信）</p>\n<p>9. 向客户再次表达感谢，并预约下一次的接触时间（回访或邀请到店）</p>",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 87,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆并查看与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3.（以上次到店体验或印象比较深刻的信息点或遗留的问题点）唤起客户回忆并做客户重点关注的卖点提醒</p>\n<p>4.1.日常跟进：</p>                                                                                                                    \n<p>1）情感维系，前期先打破僵局，取得良好沟通的开始；</p>                                                       \n<p>2）了解客户最新动态；</p>                                                                                                       \n<p>3）简单的需求分析，判定级别是否提升：</p>                                                                             \n<p>4.）向客户介绍最新价格优惠力度、装潢标准、服务、保险、上牌等具体信息</p>\n<p>4.2.日常邀约（二次到店邀约）：告知致电目的 </p>                                                                     \n<p>5. 确认对方方便到店的时间（都问封闭式问题，最多不超过三个问题，eg:您是平时还是周末有时间？那是周六还是周日？您看我们约在周六上午十点可以吗？）；</p>                                       \n<p>6.告知来店好处（结合之前了解的客户的喜好特点来设定利益，利用喜好关联来诱惑客户至店）</p>\n<p>7. 告知经销店的具体位置，并告知来店的方式（要求销售顾问对于经销店周边的环境要熟知）</p> \n<p>8.为下次联系留下伏笔（根据本次电话内容找出可跟进的话题，以备下次联系留下机会）；</p>       \n<p>9.再次做一下自我介绍，加深客户的印象，并强调到店一定记得找自己 </p>                                                              \n<p>10.询问对方是否还有其他需要帮助的，若有则继续提供咨询服务；</p>                                        \n<p>11.若无则感谢关注并祝福； </p>                                                                                                \n<p>12.等对方挂机后再挂机（若对方没有先挂，请对方先挂机）</p>                                                 \n<p>13.发送短信或者微信并再次提出邀请（可根据电话内容设置不同话术内容）</p>",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 88,
      "title": "",
      "content": "<p>1. 进行通话前的准备工作（照一下镜子，微笑调整心情、注意通话语气、回忆与客户上次通话的重要细节）</p>\n<p>2. 自我介绍 （4S店名称、自我的昵称）</p>\n<p>3. 简单告知活动主题（邀约试驾、店内活动、.....）</p>\n<p>4. 告知此次活动的特殊性（e.g. 店内优惠、到店礼包、…..）</p>\n<p>5. 突出该客户的专属性（e.g. 名额有限、专门针对某一类的客户组织的交谊会、…..）</p>                    \n<p>6.询问对方参加活动的意向程度</p>\n<p>6.1.若愿意参加， 与客户确认到店时间并且尝试邀请其亲朋好友一起到场 </p>\n<p>6.2.若客户产生拒绝邀约的意向，需探寻拒绝的原因，并作其他补救措施，告知大多数车主参加活动的兴趣点（举证法：举证一些其他客户关注的方面，尝试能否引起客户共鸣，达到从众的作用）</p>   \n<p>7.寻找话题点为下次联系留下伏笔 </p>                                                                                               \n<p>8.感谢关注并祝福</p>",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 2
    },
    {
      "id": 89,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！专业的服务，仅为专业的您量身定制！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 90,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！Jeep已不再是男士专享，女人同样拥有Jeep的精彩！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 91,
      "title": "男士（专业）",
      "content": "Jeep用实力让情怀落地，【插入/输入与客户关注点相关的产品卖点】让懂车的您感受驾驶的畅快淋漓，自此Jeep与您一起走上不凡之路！联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 92,
      "title": "女士（情怀）",
      "content": "伴随着温暖的阳光，为您送来亲切的问候。诚邀您到店体验【车型】，【插入/输入与客户关注点相关的产品卖点】Jeep专业SUV缔造者，无论身处城市，或回归自然，更多温暖，更多感动。联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 93,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练为您进行最专业的动态展示。为确保您能顺利进行试驾活动，提醒您提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 94,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练带给您不一样的惊喜。为带给您完美的试驾体验，提醒您请勿穿着高跟鞋并提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 95,
      "title": "男士（专业）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】先生，【4S店名称】诚邀您参加【活动名称】，规模空前绝后，专业性不言而喻，用Jeep的实力带您领略人生的新高度。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。＃销售顾问姓名＃敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 96,
      "title": "女士（情怀）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】女士，【4S店名称】诚邀您参加【活动名称】，与Jeep一起探享旅途中的未知与可能，我们负责懂车，您负责懂生活。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 97,
      "title": "男士（专业）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】专业的服务，迎接专业的您到来。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们以专业相会。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 98,
      "title": "女士（情怀）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】贴心的服务，为您带来贴心的关怀。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们贴心等待。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 99,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，我们对您的爱车已进行了全方位的交车前检查，专业的售后技术力量加以严格的质量把控，真正做到每个检测环节锱铢必较，确保您的爱车时刻做到如影随形。【车型】已为您准备就绪，随时蓄势待发。专业的销售团队，专业的交车仪式恭候着您明天的驾临。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 100,
      "title": "女士（情怀）",
      "content": "亲，我们对您的爱车已进行了全方位的交车检查，现您的爱车外观已如水晶般晶莹剔透，内饰更是整洁如一，当然看不见的地方我们更是以十万分认真的态度检测，由内而外予以最贴切的呵护。【车型】已打包完毕，精美的提车惊喜也随车附送。带上您的好心情及五星好评，来一场明日的甜美邂逅。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 101,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！我们将一如既往的为您提供专业的技术、优质的产品和贴心的服务，您的满意是我们永远的追求！您身边的24小时车辆管家【销售顾问姓名】祝您提车愉快，一路顺风！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 102,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！无论是5天工作日的城市生活，或是2天周末的休闲体验，您的爱车都将带给您随心所欲的旅程，【销售顾问姓名】坚信您无论走到哪里，都将成为生活的主角，并再次祝您提车愉快！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 103,
      "title": "男士（专业）",
      "content": "专业的用车，离不开专业的养车。尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。【4S店名称】专业的售后保养服务期待着您的到来！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 104,
      "title": "女士（情怀）",
      "content": "亲，爱车也要像您精致的妆容一样定期保养哟！尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。快来【4S店名称】给您的爱车来一场美美哒的保养体验吧！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 105,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 106,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 107,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 108,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 0,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 109,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！专业的服务，仅为专业的您量身定制！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 110,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！Jeep已不再是男士专享，女人同样拥有Jeep的精彩！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 111,
      "title": "男士（专业）",
      "content": "Jeep用实力让情怀落地，【插入/输入与客户关注点相关的产品卖点】让懂车的您感受驾驶的畅快淋漓，自此Jeep与您一起走上不凡之路！联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 112,
      "title": "女士（情怀）",
      "content": "伴随着温暖的阳光，为您送来亲切的问候。诚邀您到店体验【车型】，【插入/输入与客户关注点相关的产品卖点】Jeep专业SUV缔造者，无论身处城市，或回归自然，更多温暖，更多感动。联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 113,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练为您进行最专业的动态展示。为确保您能顺利进行试驾活动，提醒您提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 114,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练带给您不一样的惊喜。为带给您完美的试驾体验，提醒您请勿穿着高跟鞋并提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 115,
      "title": "男士（专业）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】先生，【4S店名称】诚邀您参加【活动名称】，规模空前绝后，专业性不言而喻，用Jeep的实力带您领略人生的新高度。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。＃销售顾问姓名＃敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 116,
      "title": "女士（情怀）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】女士，【4S店名称】诚邀您参加【活动名称】，与Jeep一起探享旅途中的未知与可能，我们负责懂车，您负责懂生活。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 117,
      "title": "男士（专业）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】专业的服务，迎接专业的您到来。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们以专业相会。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 118,
      "title": "女士（情怀）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】贴心的服务，为您带来贴心的关怀。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们贴心等待。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 119,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，我们对您的爱车已进行了全方位的交车前检查，专业的售后技术力量加以严格的质量把控，真正做到每个检测环节锱铢必较，确保您的爱车时刻做到如影随形。【车型】已为您准备就绪，随时蓄势待发。专业的销售团队，专业的交车仪式恭候着您明天的驾临。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 120,
      "title": "女士（情怀）",
      "content": "亲，我们对您的爱车已进行了全方位的交车检查，现您的爱车外观已如水晶般晶莹剔透，内饰更是整洁如一，当然看不见的地方我们更是以十万分认真的态度检测，由内而外予以最贴切的呵护。【车型】已打包完毕，精美的提车惊喜也随车附送。带上您的好心情及五星好评，来一场明日的甜美邂逅。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 121,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！我们将一如既往的为您提供专业的技术、优质的产品和贴心的服务，您的满意是我们永远的追求！您身边的24小时车辆管家【销售顾问姓名】祝您提车愉快，一路顺风！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 122,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！无论是5天工作日的城市生活，或是2天周末的休闲体验，您的爱车都将带给您随心所欲的旅程，【销售顾问姓名】坚信您无论走到哪里，都将成为生活的主角，并再次祝您提车愉快！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 123,
      "title": "男士（专业）",
      "content": "专业的用车，离不开专业的养车。尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。【4S店名称】专业的售后保养服务期待着您的到来！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 124,
      "title": "女士（情怀）",
      "content": "亲，爱车也要像您精致的妆容一样定期保养哟！尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。快来【4S店名称】给您的爱车来一场美美哒的保养体验吧！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 125,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 126,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 127,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 128,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 12,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 129,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！专业的服务，仅为专业的您量身定制！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 130,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！Jeep已不再是男士专享，女人同样拥有Jeep的精彩！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 131,
      "title": "男士（专业）",
      "content": "Jeep用实力让情怀落地，【插入/输入与客户关注点相关的产品卖点】让懂车的您感受驾驶的畅快淋漓，自此Jeep与您一起走上不凡之路！联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 132,
      "title": "女士（情怀）",
      "content": "伴随着温暖的阳光，为您送来亲切的问候。诚邀您到店体验【车型】，【插入/输入与客户关注点相关的产品卖点】Jeep专业SUV缔造者，无论身处城市，或回归自然，更多温暖，更多感动。联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 133,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练为您进行最专业的动态展示。为确保您能顺利进行试驾活动，提醒您提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 134,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练带给您不一样的惊喜。为带给您完美的试驾体验，提醒您请勿穿着高跟鞋并提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 135,
      "title": "男士（专业）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】先生，【4S店名称】诚邀您参加【活动名称】，规模空前绝后，专业性不言而喻，用Jeep的实力带您领略人生的新高度。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。＃销售顾问姓名＃敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 136,
      "title": "女士（情怀）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】女士，【4S店名称】诚邀您参加【活动名称】，与Jeep一起探享旅途中的未知与可能，我们负责懂车，您负责懂生活。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 137,
      "title": "男士（专业）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】专业的服务，迎接专业的您到来。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们以专业相会。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 138,
      "title": "女士（情怀）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】贴心的服务，为您带来贴心的关怀。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们贴心等待。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 139,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，我们对您的爱车已进行了全方位的交车前检查，专业的售后技术力量加以严格的质量把控，真正做到每个检测环节锱铢必较，确保您的爱车时刻做到如影随形。【车型】已为您准备就绪，随时蓄势待发。专业的销售团队，专业的交车仪式恭候着您明天的驾临。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 140,
      "title": "女士（情怀）",
      "content": "亲，我们对您的爱车已进行了全方位的交车检查，现您的爱车外观已如水晶般晶莹剔透，内饰更是整洁如一，当然看不见的地方我们更是以十万分认真的态度检测，由内而外予以最贴切的呵护。【车型】已打包完毕，精美的提车惊喜也随车附送。带上您的好心情及五星好评，来一场明日的甜美邂逅。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 141,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！我们将一如既往的为您提供专业的技术、优质的产品和贴心的服务，您的满意是我们永远的追求！您身边的24小时车辆管家【销售顾问姓名】祝您提车愉快，一路顺风！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 142,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！无论是5天工作日的城市生活，或是2天周末的休闲体验，您的爱车都将带给您随心所欲的旅程，【销售顾问姓名】坚信您无论走到哪里，都将成为生活的主角，并再次祝您提车愉快！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 143,
      "title": "男士（专业）",
      "content": "专业的用车，离不开专业的养车。尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。【4S店名称】专业的售后保养服务期待着您的到来！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 144,
      "title": "女士（情怀）",
      "content": "亲，爱车也要像您精致的妆容一样定期保养哟！尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。快来【4S店名称】给您的爱车来一场美美哒的保养体验吧！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 145,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 146,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 147,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 148,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 15,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 149,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！专业的服务，仅为专业的您量身定制！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 150,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！Jeep已不再是男士专享，女人同样拥有Jeep的精彩！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 151,
      "title": "男士（专业）",
      "content": "Jeep用实力让情怀落地，【插入/输入与客户关注点相关的产品卖点】让懂车的您感受驾驶的畅快淋漓，自此Jeep与您一起走上不凡之路！联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 152,
      "title": "女士（情怀）",
      "content": "伴随着温暖的阳光，为您送来亲切的问候。诚邀您到店体验【车型】，【插入/输入与客户关注点相关的产品卖点】Jeep专业SUV缔造者，无论身处城市，或回归自然，更多温暖，更多感动。联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 153,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练为您进行最专业的动态展示。为确保您能顺利进行试驾活动，提醒您提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 154,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练带给您不一样的惊喜。为带给您完美的试驾体验，提醒您请勿穿着高跟鞋并提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 155,
      "title": "男士（专业）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】先生，【4S店名称】诚邀您参加【活动名称】，规模空前绝后，专业性不言而喻，用Jeep的实力带您领略人生的新高度。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。＃销售顾问姓名＃敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 156,
      "title": "女士（情怀）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】女士，【4S店名称】诚邀您参加【活动名称】，与Jeep一起探享旅途中的未知与可能，我们负责懂车，您负责懂生活。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 157,
      "title": "男士（专业）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】专业的服务，迎接专业的您到来。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们以专业相会。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 158,
      "title": "女士（情怀）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】贴心的服务，为您带来贴心的关怀。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们贴心等待。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 159,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，我们对您的爱车已进行了全方位的交车前检查，专业的售后技术力量加以严格的质量把控，真正做到每个检测环节锱铢必较，确保您的爱车时刻做到如影随形。【车型】已为您准备就绪，随时蓄势待发。专业的销售团队，专业的交车仪式恭候着您明天的驾临。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 160,
      "title": "女士（情怀）",
      "content": "亲，我们对您的爱车已进行了全方位的交车检查，现您的爱车外观已如水晶般晶莹剔透，内饰更是整洁如一，当然看不见的地方我们更是以十万分认真的态度检测，由内而外予以最贴切的呵护。【车型】已打包完毕，精美的提车惊喜也随车附送。带上您的好心情及五星好评，来一场明日的甜美邂逅。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 161,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！我们将一如既往的为您提供专业的技术、优质的产品和贴心的服务，您的满意是我们永远的追求！您身边的24小时车辆管家【销售顾问姓名】祝您提车愉快，一路顺风！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 162,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！无论是5天工作日的城市生活，或是2天周末的休闲体验，您的爱车都将带给您随心所欲的旅程，【销售顾问姓名】坚信您无论走到哪里，都将成为生活的主角，并再次祝您提车愉快！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 163,
      "title": "男士（专业）",
      "content": "专业的用车，离不开专业的养车。尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。【4S店名称】专业的售后保养服务期待着您的到来！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 164,
      "title": "女士（情怀）",
      "content": "亲，爱车也要像您精致的妆容一样定期保养哟！尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。快来【4S店名称】给您的爱车来一场美美哒的保养体验吧！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 165,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 166,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 167,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 168,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 19,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 169,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！专业的服务，仅为专业的您量身定制！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 170,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，感谢您的莅临！我是刚刚接待您的销售顾问【销售顾问姓名】，如有任何问题，可随时与我联系！Jeep已不再是男士专享，女人同样拥有Jeep的精彩！【销售顾问姓名】24小时竭诚为您服务，电话【销售顾问电话】，也可添加个人微信号【销售顾问微信号】，随时为您解答。",
      "url": "1",
      "valid": false,
      "description": "离店回访",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 171,
      "title": "男士（专业）",
      "content": "Jeep用实力让情怀落地，【插入/输入与客户关注点相关的产品卖点】让懂车的您感受驾驶的畅快淋漓，自此Jeep与您一起走上不凡之路！联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 172,
      "title": "女士（情怀）",
      "content": "伴随着温暖的阳光，为您送来亲切的问候。诚邀您到店体验【车型】，【插入/输入与客户关注点相关的产品卖点】Jeep专业SUV缔造者，无论身处城市，或回归自然，更多温暖，更多感动。联系方式：【销售顾问电话】，【销售顾问姓名】",
      "url": "1",
      "valid": false,
      "description": "日常跟进",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 173,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】先生，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练为您进行最专业的动态展示。为确保您能顺利进行试驾活动，提醒您提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 174,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】女士，恭喜您已成功预约XX月XX日的试驾活动。届时针对您对于【车型】的关注，我们将安排专业的试驾教练带给您不一样的惊喜。为带给您完美的试驾体验，提醒您请勿穿着高跟鞋并提前准备好驾照。如有任何变动及问题，欢迎随时拨打【销售顾问姓名】24小时服务热线【销售顾问电话】，【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "试驾预约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 175,
      "title": "男士（专业）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】先生，【4S店名称】诚邀您参加【活动名称】，规模空前绝后，专业性不言而喻，用Jeep的实力带您领略人生的新高度。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。＃销售顾问姓名＃敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 176,
      "title": "女士（情怀）",
      "content": "一天时间，改变一生追求。尊敬的【客户姓名】女士，【4S店名称】诚邀您参加【活动名称】，与Jeep一起探享旅途中的未知与可能，我们负责懂车，您负责懂生活。【活动时间】，【活动地点】，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。【销售顾问姓名】敬候您的驾临。",
      "url": "1",
      "valid": false,
      "description": "活动邀约",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 177,
      "title": "男士（专业）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】专业的服务，迎接专业的您到来。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们以专业相会。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 178,
      "title": "女士（情怀）",
      "content": "今日本市最高气温**，最低气温**，提醒您出门前关注气候变化。为方便您的莅临，以下线路供您参考：驾车XXXXXX；公共交通XXXXX。广汽菲克【4S店名称】贴心的服务，为您带来贴心的关怀。【4S店地址】，【销售顾问姓名】【销售顾问电话】，【预约时间】，我们贴心等待。",
      "url": "1",
      "valid": false,
      "description": "到店提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 179,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，我们对您的爱车已进行了全方位的交车前检查，专业的售后技术力量加以严格的质量把控，真正做到每个检测环节锱铢必较，确保您的爱车时刻做到如影随形。【车型】已为您准备就绪，随时蓄势待发。专业的销售团队，专业的交车仪式恭候着您明天的驾临。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 180,
      "title": "女士（情怀）",
      "content": "亲，我们对您的爱车已进行了全方位的交车检查，现您的爱车外观已如水晶般晶莹剔透，内饰更是整洁如一，当然看不见的地方我们更是以十万分认真的态度检测，由内而外予以最贴切的呵护。【车型】已打包完毕，精美的提车惊喜也随车附送。带上您的好心情及五星好评，来一场明日的甜美邂逅。温馨提示：请挈带好您的身份证及暂住证。",
      "url": "1",
      "valid": false,
      "description": "交车提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 181,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！我们将一如既往的为您提供专业的技术、优质的产品和贴心的服务，您的满意是我们永远的追求！您身边的24小时车辆管家【销售顾问姓名】祝您提车愉快，一路顺风！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 182,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，非常感谢您对广汽菲克【车型】的支持与厚爱！无论是5天工作日的城市生活，或是2天周末的休闲体验，您的爱车都将带给您随心所欲的旅程，【销售顾问姓名】坚信您无论走到哪里，都将成为生活的主角，并再次祝您提车愉快！",
      "url": "1",
      "valid": false,
      "description": "提车关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 183,
      "title": "男士（专业）",
      "content": "专业的用车，离不开专业的养车。尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。【4S店名称】专业的售后保养服务期待着您的到来！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 184,
      "title": "女士（情怀）",
      "content": "亲，爱车也要像您精致的妆容一样定期保养哟！尊敬的【客户姓名】车主，广汽菲克友情提醒您，您的爱车【车型】保养时间将近，请于指定公里数或日期前至广汽菲克指定经销商进行车辆专业检修及保养，也可提前通过关注广汽菲克全境界服务微信公众号，进行在线保养预约。快来【4S店名称】给您的爱车来一场美美哒的保养体验吧！",
      "url": "1",
      "valid": false,
      "description": "保养提醒",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 185,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 186,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，【节日名称】即将来临，【车型】祝您节日快乐！愿祝福萦绕着你，在你缤纷的人生之旅，Jeep将永远与您和您的梦想接壤。在这个属于您的精彩日子里，送上我最诚挚的祝福，愿你生活如意，工作顺利，好上加好，福中更福！【4S店名称】",
      "url": "1",
      "valid": false,
      "description": "特殊节日关怀",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 187,
      "title": "男士（专业）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    },
    {
      "id": 188,
      "title": "女士（情怀）",
      "content": "尊敬的【客户姓名】车主，今明两天有大雨，请勿涉水行车，如车辆遇水熄火，请勿再次启动。如遇特殊情况，【4S店名称】最专业的服务团队随时为您排忧解难，【销售顾问姓名】【销售顾问电话】，也可通过关注广汽菲克全境界服务微信公众号，一键尊享24小时道路救援服务。",
      "url": "1",
      "valid": false,
      "description": "温馨提示",
      "createdDate": 1490695200000,
      "modifiedDate": null,
      "modelID": 21,
      "modelName": null,
      "brandID": 0,
      "talkLibraryType": 3
    }
  ]
