/**
 * Created by zhongzhengkai on 2016/11/8.
 */

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

//客户列表
export const GET_CONTACT_LIST = 'GET_CONTACT_LIST';
export const GET_ACCOUNT_ROLE = 'GET_ACCOUNT_ROLE';
export const GET_CUSTOMER_INFO = 'GET_CUSTOMER_INFO';
export const GET_COMMUNICATE_HISTORY = 'GET_COMMUNICATE_HISTORY';
export const FOLLOW_UP = 'FOLLOW_UP';
export const UPDATE_CUSTOMER_INFO = 'UPDATE_CUSTOMER_INFO';
export const INSERT_CUSTOMER_INFO = 'INSERT_CUSTOMER_INFO';
export const CHECK_DATA_STATUS = 'CHECK_DATA_STATUS';

//登录相关
export const GET_BASE_DATA_VERSION = 'GET_BASE_DATA_VERSION';
export const GET_DICT_CHANNEL = 'GET_DICT_CHANNEL';
export const GET_DICT_CUSTOMER_STATUS = 'GET_DICT_CUSTOMER_STATUS';
export const GET_DICT_DEALER = 'GET_DICT_DEALER';
export const GET_DICT_PRODUCT = 'GET_DICT_PRODUCT';
export const GET_DICT_GEOGRAPHY = 'GET_DICT_GEOGRAPHY';
export const GET_DICT_DICTIONARY = 'GET_DICT_DICTIONARY';
export const GET_DICT_SYS_ROLE = 'GET_DICT_SYS_ROLE';
export const GET_DICT_OPPORTUNITY_LEVEL = 'GET_DICT_OPPORTUNITY_LEVEL';
export const GET_DICT_PRODUCT_SKU = 'GET_DICT_PRODUCT_SKU';
export const GET_DICT_DEALER_PRODUCT = 'GET_DICT_DEALER_PRODUCT';
export const GET_DICT_LICENSE_INFO = 'GET_DICT_LICENSE_INFO';

//今日任务模块
export const GET_TODAY_TASKS = 'GET_TODAY_TASKS';
export const GET_TODAY_TASKS_TALK_LIB = 'GET_TODAY_TASKS_TALK_LIB';
export const SEND_COMMUNICATION_HISTORY = 'SEND_COMMUNICATION_HISTORY';
export const TODAY_TASKS_PREV_PAGE = 'TODAY_TASKS_PREV_PAGE';
export const TODAY_TASKS_NEXT_PAGE = 'TODAY_TASKS_NEXT_PAGE';

//话术库模块，获取话术数据
export const GET_TALK_LIB = 'GET_TALK_LIB';

//内容列表
export const GET_CAR_GROUPS = 'GET_CAR_GROUPS';
export const GET_ARTICLE_TYPES = 'GET_ARTICLE_TYPES';
export const SEARCH_ARTICLE_LIST = 'SEARCH_ARTICLE_LIST';
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';

//试乘试驾
export const INSERT_TEST_DRIVE_INFO = 'INSERT_TEST_DRIVE_INFO'; 
export const GET_LIST_TEST_DRIVE = 'GET_LIST_TEST_DRIVE';
export const GET_CONTACT_INFO_BY_PHONE = 'GET_CONTACT_INFO_BY_PHONE';
export const GET_LIST_FEEDBACK_INFO = 'GET_LIST_FEEDBACK_INFO';
export const GET_LIST_FEEDBACK = 'GET_LIST_FEEDBACK';
export const INSERT_FEEDBACK_INFO = 'INSERT_FEEDBACK_INFO';
export const UPLOAD_CARD = 'UPLOAD_CARD';
export const UPDATE_TEST_DRIVE_INFO = 'UPDATE_TEST_DRIVE_INFO';
export const DOWN_LOAD_PDF = 'DOWN_LOAD_PDF';

//主页
export const GET_TODAY_TASK_NUM = 'GET_TODAY_TASK_NUM';
export const GET_TODAY_RECOMMEND_CONTENT = 'GET_TODAY_RECOMMEND_CONTENT';

//我的报表
export const GET_MY_REPORT_DATA = 'GET_MY_REPORT_DATA';
export const GET_COMPARISON_DATA = 'GET_COMPARISON_DATA';
export const CHANGE_COMPARE_PERSON = 'CHANGE_COMPARE_PERSON';

